### ISSUE TITLE
Handle IF EXISTS

### ISSUE THREAD

**Issue by SteveFeldman** [ScoRobi/baltimore-crime#1]
Scott,

Minor fix, but change your DROP in CREATE_TABLE_CRIME.sql

DROP TABLE IF EXISTS baltimore_crime.crime;

**Comment by ScoRobi** [comment]
This has been corrected in https://github.com/ScoRobi/baltimore-crime/commit/4c90e0537d8d6f01056744d8de185343e81889ee. Also fixed a similar issue in the database creation script.
